public class afl {
	public static final afh a;
	public static final afh b;
	public static final afh c;
	public static final afh d;
	public static final afh e;
	public static final afh f;
	public static final aea g;
	public static final afh h;
	public static final afh i;
	public static final afh j;
	public static final afh k;
	public static final afh l;
	public static final afh m;
	public static final afh n;
	public static final afh o;
	public static final afh p;
	public static final afh q;
	public static final afh r;
	public static final afh s;
	public static final afh t;
	public static final afh u;
	public static final afh v;
	public static final afh w;
	public static final afh x;
	public static final afh y;
	public static final afh z;
	public static final afh A;
	public static final afh B;
	public static final afh C;
	public static final afh D;
	public static final afh E;
	public static final afh F;
	public static final afh G;
	public static final afh H;
	public static final afh I;
	public static final afh J;
	public static final afh K;
	public static final afh L;
	public static final afh M;
	public static final afh N;
	public static final afh O;
	public static final afh P;
	public static final afh Q;
	public static final afh R;
	public static final afh S;
	public static final adp T;
	public static final adp U;
	public static final adp V;
	public static final adp W;
	public static final adp X;
	public static final adp Y;
	public static final adp Z;
	public static final adp aa;
	public static final adp ab;
	public static final adp ac;
	public static final adp ad;
	public static final adp ae;
	public static final adp af;
	public static final adp ag;
	public static final adp ah;
	public static final adp ai;
	public static final adp aj;
	public static final adp ak;
	public static final adp al;
	public static final adp am;
	public static final afh an;
	public static final afh ao;
	public static final afh ap;
	public static final afh aq;
	public static final afh ar;
	public static final afh as;
	public static final afh at;
	public static final afh au;
	public static final afh av;
	public static final afh aw;
	public static final afh ax;
	public static final afh ay;
	public static final afh az;
	public static final afh aA;
	public static final afh aB;
	public static final afh aC;
	public static final afh aD;
	public static final afh aE;
	public static final afh aF;
	public static final afh aG;
	public static final afh aH;
	public static final afh aI;
	public static final afh aJ;
	public static final afh aK;
	public static final afh aL;
	public static final afh aM;
	public static final afh aN;
	public static final afh aO;
	public static final afh aP;
	public static final afh aQ;
	public static final afh aR;
	public static final afh aS;
	public static final afh aT;
	public static final afh aU;
	public static final afh aV;
	public static final afh aW;
	public static final afh aX;
	public static final afh aY;
	public static final afb aZ;
	public static final afh ba;
	public static final afh bb;
	public static final afh bc;
	public static final afh bd;
	public static final afh be;
	public static final afh bf;
	public static final afh bg;
	public static final afh bh;
	public static final afh bi;
	public static final afh bj;
	public static final afh bk;
	public static final afp bl;
	public static final age bm;
	public static final afh bn;
	public static final afh bo;
	public static final afh bp;
	public static final afh bq;
	public static final afh br;
	public static final afh bs;
	public static final afh bt;
	public static final afh bu;
	public static final afh bv;
	public static final afh bw;
	public static final afh bx;
	public static final afh by;
	public static final afh bz;
	public static final afh bA;
	public static final afh bB;
	public static final afh bC;
	public static final afh bD;
	public static final afh bE;
	public static final afh bF;
	public static final afh bG;
	public static final afw bH;
	public static final afw bI;
	public static final afw bJ;
	public static final afh bK;
	public static final afh bL;
	public static final afh bM;
	public static final afh bN;
	public static final afh bO;
	public static final afh bP;
	public static final afh bQ;
	public static final afh bR;
	public static final afh bS;
	public static final afh bT;
	public static final afh bU;
	public static final afh bV;
	public static final afh bW;
	public static final afh bX;
	public static final afh bY;
	public static final afh bZ;
	public static final afh ca;
	public static final afh cb;
	public static final afh cc;
	public static final afh cd;
	public static final afh ce;
	public static final afh cf;
	public static final aer cg;
	public static final afh ch;
	public static final afh ci;
	public static final afh cj;
	public static final afh ck;
	public static final afh cl;
	public static final afh cm;
	public static final afh cn;
	public static final aes co;
	public static final afh cp;
	public static final afh cq;
	public static final afh cr;
	public static final afh cs;
	public static final afh ct;
	public static final adq cu;
	public static final afh cv;
	public static final afh cw;
	public static final afh cx;
	public static final afh cy;
	public static final afh cz;
	public static final afh cA;
	public static final afh cB;
	public static final afh cC;
	public static final afh cD;
	public static final afh cE;
	public static final afh cF;
	public static final afh cG;
	public static final afh cH;
	public static final afh cI;
	public static final afh cJ;
	public static final afh cK;
	public static final afh cL;
	public static final afh cM;
	public static final afh cN;
	public static final afh cO;
	public static final afh cP;
	public static final afh cQ;
	public static final afh cR;
	public static final afh cS;
	public static final afh cT;
	public static final afh cU;
	public static final afh cV;
	public static final afh cW;
	public static final afh cX;
	public static final afh cY;
	public static final afh cZ;
	public static final afh da;

	private static afh a(String string) {
		afh afh2 = afh.g.c(new kq(string));
		if (afh2 == null) {
			throw new IllegalStateException("Invalid Item requested: " + string);
		} else {
			return afh2;
		}
	}

	static {
		if (!kt.a()) {
			throw new RuntimeException("Accessed Items before Bootstrap!");
		} else {
			a = a("air");
			b = a("iron_shovel");
			c = a("iron_pickaxe");
			d = a("iron_axe");
			e = a("flint_and_steel");
			f = a("apple");
			g = (aea)a("bow");
			h = a("arrow");
			i = a("spectral_arrow");
			j = a("tipped_arrow");
			k = a("coal");
			l = a("diamond");
			m = a("iron_ingot");
			n = a("gold_ingot");
			o = a("iron_sword");
			p = a("wooden_sword");
			q = a("wooden_shovel");
			r = a("wooden_pickaxe");
			s = a("wooden_axe");
			t = a("stone_sword");
			u = a("stone_shovel");
			v = a("stone_pickaxe");
			w = a("stone_axe");
			x = a("diamond_sword");
			y = a("diamond_shovel");
			z = a("diamond_pickaxe");
			A = a("diamond_axe");
			B = a("stick");
			C = a("bowl");
			D = a("mushroom_stew");
			E = a("golden_sword");
			F = a("golden_shovel");
			G = a("golden_pickaxe");
			H = a("golden_axe");
			I = a("string");
			J = a("feather");
			K = a("gunpowder");
			L = a("wooden_hoe");
			M = a("stone_hoe");
			N = a("iron_hoe");
			O = a("diamond_hoe");
			P = a("golden_hoe");
			Q = a("wheat_seeds");
			R = a("wheat");
			S = a("bread");
			T = (adp)a("leather_helmet");
			U = (adp)a("leather_chestplate");
			V = (adp)a("leather_leggings");
			W = (adp)a("leather_boots");
			X = (adp)a("chainmail_helmet");
			Y = (adp)a("chainmail_chestplate");
			Z = (adp)a("chainmail_leggings");
			aa = (adp)a("chainmail_boots");
			ab = (adp)a("iron_helmet");
			ac = (adp)a("iron_chestplate");
			ad = (adp)a("iron_leggings");
			ae = (adp)a("iron_boots");
			af = (adp)a("diamond_helmet");
			ag = (adp)a("diamond_chestplate");
			ah = (adp)a("diamond_leggings");
			ai = (adp)a("diamond_boots");
			aj = (adp)a("golden_helmet");
			ak = (adp)a("golden_chestplate");
			al = (adp)a("golden_leggings");
			am = (adp)a("golden_boots");
			an = a("flint");
			ao = a("porkchop");
			ap = a("cooked_porkchop");
			aq = a("painting");
			ar = a("golden_apple");
			as = a("sign");
			at = a("wooden_door");
			au = a("spruce_door");
			av = a("birch_door");
			aw = a("jungle_door");
			ax = a("acacia_door");
			ay = a("dark_oak_door");
			az = a("bucket");
			aA = a("water_bucket");
			aB = a("lava_bucket");
			aC = a("minecart");
			aD = a("saddle");
			aE = a("iron_door");
			aF = a("redstone");
			aG = a("snowball");
			aH = a("boat");
			aI = a("spruce_boat");
			aJ = a("birch_boat");
			aK = a("jungle_boat");
			aL = a("acacia_boat");
			aM = a("dark_oak_boat");
			aN = a("leather");
			aO = a("milk_bucket");
			aP = a("brick");
			aQ = a("clay_ball");
			aR = a("reeds");
			aS = a("paper");
			aT = a("book");
			aU = a("slime_ball");
			aV = a("chest_minecart");
			aW = a("furnace_minecart");
			aX = a("egg");
			aY = a("compass");
			aZ = (afb)a("fishing_rod");
			ba = a("clock");
			bb = a("glowstone_dust");
			bc = a("fish");
			bd = a("cooked_fish");
			be = a("dye");
			bf = a("bone");
			bg = a("sugar");
			bh = a("cake");
			bi = a("bed");
			bj = a("repeater");
			bk = a("cookie");
			bl = (afp)a("filled_map");
			bm = (age)a("shears");
			bn = a("melon");
			bo = a("pumpkin_seeds");
			bp = a("melon_seeds");
			bq = a("beef");
			br = a("cooked_beef");
			bs = a("chicken");
			bt = a("cooked_chicken");
			bu = a("mutton");
			bv = a("cooked_mutton");
			bw = a("rabbit");
			bx = a("cooked_rabbit");
			by = a("rabbit_stew");
			bz = a("rabbit_foot");
			bA = a("rabbit_hide");
			bB = a("rotten_flesh");
			bC = a("ender_pearl");
			bD = a("blaze_rod");
			bE = a("ghast_tear");
			bF = a("gold_nugget");
			bG = a("nether_wart");
			bH = (afw)a("potion");
			bI = (afw)a("splash_potion");
			bJ = (afw)a("lingering_potion");
			bK = a("glass_bottle");
			bL = a("dragon_breath");
			bM = a("spider_eye");
			bN = a("fermented_spider_eye");
			bO = a("blaze_powder");
			bP = a("magma_cream");
			bQ = a("brewing_stand");
			bR = a("cauldron");
			bS = a("ender_eye");
			bT = a("speckled_melon");
			bU = a("spawn_egg");
			bV = a("experience_bottle");
			bW = a("fire_charge");
			bX = a("writable_book");
			bY = a("written_book");
			bZ = a("emerald");
			ca = a("item_frame");
			cb = a("flower_pot");
			cc = a("carrot");
			cd = a("potato");
			ce = a("baked_potato");
			cf = a("poisonous_potato");
			cg = (aer)a("map");
			ch = a("golden_carrot");
			ci = a("skull");
			cj = a("carrot_on_a_stick");
			ck = a("nether_star");
			cl = a("pumpkin_pie");
			cm = a("fireworks");
			cn = a("firework_charge");
			co = (aes)a("enchanted_book");
			cp = a("comparator");
			cq = a("netherbrick");
			cr = a("quartz");
			cs = a("tnt_minecart");
			ct = a("hopper_minecart");
			cu = (adq)a("armor_stand");
			cv = a("iron_horse_armor");
			cw = a("golden_horse_armor");
			cx = a("diamond_horse_armor");
			cy = a("lead");
			cz = a("name_tag");
			cA = a("command_block_minecart");
			cB = a("record_13");
			cC = a("record_cat");
			cD = a("record_blocks");
			cE = a("record_chirp");
			cF = a("record_far");
			cG = a("record_mall");
			cH = a("record_mellohi");
			cI = a("record_stal");
			cJ = a("record_strad");
			cK = a("record_ward");
			cL = a("record_11");
			cM = a("record_wait");
			cN = a("prismarine_shard");
			cO = a("prismarine_crystals");
			cP = a("banner");
			cQ = a("end_crystal");
			cR = a("shield");
			cS = a("elytra");
			cT = a("chorus_fruit");
			cU = a("chorus_fruit_popped");
			cV = a("beetroot_seeds");
			cW = a("beetroot");
			cX = a("beetroot_soup");
			cY = a("totem_of_undying");
			cZ = a("shulker_shell");
			da = a("iron_nugget");
		}
	}
}
