public class nn {
	public static final nm a;
	public static final nm b;
	public static final nm c;
	public static final nm d;
	public static final nm e;
	public static final nm f;
	public static final nm g;
	public static final nm h;
	public static final nm i;
	public static final nm j;
	public static final nm k;
	public static final nm l;
	public static final nm m;
	public static final nm n;
	public static final nm o;
	public static final nm p;
	public static final nm q;
	public static final nm r;
	public static final nm s;
	public static final nm t;
	public static final nm u;
	public static final nm v;
	public static final nm w;
	public static final nm x;
	public static final nm y;
	public static final nm z;
	public static final nm A;
	public static final nm B;
	public static final nm C;
	public static final nm D;
	public static final nm E;
	public static final nm F;
	public static final nm G;
	public static final nm H;
	public static final nm I;
	public static final nm J;
	public static final nm K;
	public static final nm L;
	public static final nm M;
	public static final nm N;
	public static final nm O;
	public static final nm P;
	public static final nm Q;
	public static final nm R;
	public static final nm S;
	public static final nm T;
	public static final nm U;
	public static final nm V;
	public static final nm W;
	public static final nm X;
	public static final nm Y;
	public static final nm Z;
	public static final nm aa;
	public static final nm ab;
	public static final nm ac;
	public static final nm ad;
	public static final nm ae;
	public static final nm af;
	public static final nm ag;
	public static final nm ah;
	public static final nm ai;
	public static final nm aj;
	public static final nm ak;
	public static final nm al;
	public static final nm am;
	public static final nm an;
	public static final nm ao;
	public static final nm ap;
	public static final nm aq;
	public static final nm ar;
	public static final nm as;
	public static final nm at;
	public static final nm au;
	public static final nm av;
	public static final nm aw;
	public static final nm ax;
	public static final nm ay;
	public static final nm az;
	public static final nm aA;
	public static final nm aB;
	public static final nm aC;
	public static final nm aD;
	public static final nm aE;
	public static final nm aF;
	public static final nm aG;
	public static final nm aH;
	public static final nm aI;
	public static final nm aJ;
	public static final nm aK;
	public static final nm aL;
	public static final nm aM;
	public static final nm aN;
	public static final nm aO;
	public static final nm aP;
	public static final nm aQ;
	public static final nm aR;
	public static final nm aS;
	public static final nm aT;
	public static final nm aU;
	public static final nm aV;
	public static final nm aW;
	public static final nm aX;
	public static final nm aY;
	public static final nm aZ;
	public static final nm ba;
	public static final nm bb;
	public static final nm bc;
	public static final nm bd;
	public static final nm be;
	public static final nm bf;
	public static final nm bg;
	public static final nm bh;
	public static final nm bi;
	public static final nm bj;
	public static final nm bk;
	public static final nm bl;
	public static final nm bm;
	public static final nm bn;
	public static final nm bo;
	public static final nm bp;
	public static final nm bq;
	public static final nm br;
	public static final nm bs;
	public static final nm bt;
	public static final nm bu;
	public static final nm bv;
	public static final nm bw;
	public static final nm bx;
	public static final nm by;
	public static final nm bz;
	public static final nm bA;
	public static final nm bB;
	public static final nm bC;
	public static final nm bD;
	public static final nm bE;
	public static final nm bF;
	public static final nm bG;
	public static final nm bH;
	public static final nm bI;
	public static final nm bJ;
	public static final nm bK;
	public static final nm bL;
	public static final nm bM;
	public static final nm bN;
	public static final nm bO;
	public static final nm bP;
	public static final nm bQ;
	public static final nm bR;
	public static final nm bS;
	public static final nm bT;
	public static final nm bU;
	public static final nm bV;
	public static final nm bW;
	public static final nm bX;
	public static final nm bY;
	public static final nm bZ;
	public static final nm ca;
	public static final nm cb;
	public static final nm cc;
	public static final nm cd;
	public static final nm ce;
	public static final nm cf;
	public static final nm cg;
	public static final nm ch;
	public static final nm ci;
	public static final nm cj;
	public static final nm ck;
	public static final nm cl;
	public static final nm cm;
	public static final nm cn;
	public static final nm co;
	public static final nm cp;
	public static final nm cq;
	public static final nm cr;
	public static final nm cs;
	public static final nm ct;
	public static final nm cu;
	public static final nm cv;
	public static final nm cw;
	public static final nm cx;
	public static final nm cy;
	public static final nm cz;
	public static final nm cA;
	public static final nm cB;
	public static final nm cC;
	public static final nm cD;
	public static final nm cE;
	public static final nm cF;
	public static final nm cG;
	public static final nm cH;
	public static final nm cI;
	public static final nm cJ;
	public static final nm cK;
	public static final nm cL;
	public static final nm cM;
	public static final nm cN;
	public static final nm cO;
	public static final nm cP;
	public static final nm cQ;
	public static final nm cR;
	public static final nm cS;
	public static final nm cT;
	public static final nm cU;
	public static final nm cV;
	public static final nm cW;
	public static final nm cX;
	public static final nm cY;
	public static final nm cZ;
	public static final nm da;
	public static final nm db;
	public static final nm dc;
	public static final nm dd;
	public static final nm de;
	public static final nm df;
	public static final nm dg;
	public static final nm dh;
	public static final nm di;
	public static final nm dj;
	public static final nm dk;
	public static final nm dl;
	public static final nm dm;
	public static final nm dn;
	public static final nm do;
	public static final nm dp;
	public static final nm dq;
	public static final nm dr;
	public static final nm ds;
	public static final nm dt;
	public static final nm du;
	public static final nm dv;
	public static final nm dw;
	public static final nm dx;
	public static final nm dy;
	public static final nm dz;
	public static final nm dA;
	public static final nm dB;
	public static final nm dC;
	public static final nm dD;
	public static final nm dE;
	public static final nm dF;
	public static final nm dG;
	public static final nm dH;
	public static final nm dI;
	public static final nm dJ;
	public static final nm dK;
	public static final nm dL;
	public static final nm dM;
	public static final nm dN;
	public static final nm dO;
	public static final nm dP;
	public static final nm dQ;
	public static final nm dR;
	public static final nm dS;
	public static final nm dT;
	public static final nm dU;
	public static final nm dV;
	public static final nm dW;
	public static final nm dX;
	public static final nm dY;
	public static final nm dZ;
	public static final nm ea;
	public static final nm eb;
	public static final nm ec;
	public static final nm ed;
	public static final nm ee;
	public static final nm ef;
	public static final nm eg;
	public static final nm eh;
	public static final nm ei;
	public static final nm ej;
	public static final nm ek;
	public static final nm el;
	public static final nm em;
	public static final nm en;
	public static final nm eo;
	public static final nm ep;
	public static final nm eq;
	public static final nm er;
	public static final nm es;
	public static final nm et;
	public static final nm eu;
	public static final nm ev;
	public static final nm ew;
	public static final nm ex;
	public static final nm ey;
	public static final nm ez;
	public static final nm eA;
	public static final nm eB;
	public static final nm eC;
	public static final nm eD;
	public static final nm eE;
	public static final nm eF;
	public static final nm eG;
	public static final nm eH;
	public static final nm eI;
	public static final nm eJ;
	public static final nm eK;
	public static final nm eL;
	public static final nm eM;
	public static final nm eN;
	public static final nm eO;
	public static final nm eP;
	public static final nm eQ;
	public static final nm eR;
	public static final nm eS;
	public static final nm eT;
	public static final nm eU;
	public static final nm eV;
	public static final nm eW;
	public static final nm eX;
	public static final nm eY;
	public static final nm eZ;
	public static final nm fa;
	public static final nm fb;
	public static final nm fc;
	public static final nm fd;
	public static final nm fe;
	public static final nm ff;
	public static final nm fg;
	public static final nm fh;
	public static final nm fi;
	public static final nm fj;
	public static final nm fk;
	public static final nm fl;
	public static final nm fm;
	public static final nm fn;
	public static final nm fo;
	public static final nm fp;
	public static final nm fq;
	public static final nm fr;
	public static final nm fs;
	public static final nm ft;
	public static final nm fu;
	public static final nm fv;
	public static final nm fw;
	public static final nm fx;
	public static final nm fy;
	public static final nm fz;
	public static final nm fA;
	public static final nm fB;
	public static final nm fC;
	public static final nm fD;
	public static final nm fE;
	public static final nm fF;
	public static final nm fG;
	public static final nm fH;
	public static final nm fI;
	public static final nm fJ;
	public static final nm fK;
	public static final nm fL;
	public static final nm fM;
	public static final nm fN;
	public static final nm fO;
	public static final nm fP;
	public static final nm fQ;
	public static final nm fR;
	public static final nm fS;
	public static final nm fT;
	public static final nm fU;
	public static final nm fV;
	public static final nm fW;
	public static final nm fX;
	public static final nm fY;
	public static final nm fZ;
	public static final nm ga;
	public static final nm gb;
	public static final nm gc;
	public static final nm gd;
	public static final nm ge;
	public static final nm gf;
	public static final nm gg;
	public static final nm gh;
	public static final nm gi;
	public static final nm gj;
	public static final nm gk;
	public static final nm gl;
	public static final nm gm;
	public static final nm gn;
	public static final nm go;
	public static final nm gp;
	public static final nm gq;
	public static final nm gr;
	public static final nm gs;
	public static final nm gt;
	public static final nm gu;
	public static final nm gv;
	public static final nm gw;
	public static final nm gx;
	public static final nm gy;
	public static final nm gz;
	public static final nm gA;
	public static final nm gB;
	public static final nm gC;
	public static final nm gD;
	public static final nm gE;
	public static final nm gF;
	public static final nm gG;
	public static final nm gH;
	public static final nm gI;
	public static final nm gJ;
	public static final nm gK;
	public static final nm gL;
	public static final nm gM;
	public static final nm gN;
	public static final nm gO;
	public static final nm gP;
	public static final nm gQ;
	public static final nm gR;
	public static final nm gS;
	public static final nm gT;
	public static final nm gU;
	public static final nm gV;
	public static final nm gW;
	public static final nm gX;
	public static final nm gY;
	public static final nm gZ;
	public static final nm ha;
	public static final nm hb;
	public static final nm hc;
	public static final nm hd;
	public static final nm he;
	public static final nm hf;
	public static final nm hg;
	public static final nm hh;
	public static final nm hi;
	public static final nm hj;
	public static final nm hk;
	public static final nm hl;
	public static final nm hm;
	public static final nm hn;
	public static final nm ho;
	public static final nm hp;
	public static final nm hq;
	public static final nm hr;
	public static final nm hs;
	public static final nm ht;
	public static final nm hu;
	public static final nm hv;
	public static final nm hw;
	public static final nm hx;
	public static final nm hy;
	public static final nm hz;
	public static final nm hA;
	public static final nm hB;
	public static final nm hC;
	public static final nm hD;
	public static final nm hE;
	public static final nm hF;
	public static final nm hG;
	public static final nm hH;
	public static final nm hI;
	public static final nm hJ;
	public static final nm hK;
	public static final nm hL;
	public static final nm hM;
	public static final nm hN;
	public static final nm hO;
	public static final nm hP;
	public static final nm hQ;
	public static final nm hR;
	public static final nm hS;
	public static final nm hT;
	public static final nm hU;
	public static final nm hV;
	public static final nm hW;
	public static final nm hX;
	public static final nm hY;
	public static final nm hZ;
	public static final nm ia;
	public static final nm ib;
	public static final nm ic;
	public static final nm id;
	public static final nm ie;
	public static final nm if;
	public static final nm ig;
	public static final nm ih;
	public static final nm ii;
	public static final nm ij;
	public static final nm ik;
	public static final nm il;
	public static final nm im;
	public static final nm in;
	public static final nm io;
	public static final nm ip;
	public static final nm iq;
	public static final nm ir;
	public static final nm is;
	public static final nm it;
	public static final nm iu;
	public static final nm iv;
	public static final nm iw;
	public static final nm ix;
	public static final nm iy;

	private static nm a(String string) {
		nm nm2 = nm.a.c(new kq(string));
		if (nm2 == null) {
			throw new IllegalStateException("Invalid Sound requested: " + string);
		} else {
			return nm2;
		}
	}

	static {
		if (!kt.a()) {
			throw new RuntimeException("Accessed Sounds before Bootstrap!");
		} else {
			a = a("ambient.cave");
			b = a("block.anvil.break");
			c = a("block.anvil.destroy");
			d = a("block.anvil.fall");
			e = a("block.anvil.hit");
			f = a("block.anvil.land");
			g = a("block.anvil.place");
			h = a("block.anvil.step");
			i = a("block.anvil.use");
			j = a("entity.armorstand.break");
			k = a("entity.armorstand.fall");
			l = a("entity.armorstand.hit");
			m = a("entity.armorstand.place");
			n = a("item.armor.equip_chain");
			o = a("item.armor.equip_diamond");
			p = a("item.armor.equip_elytra");
			q = a("item.armor.equip_generic");
			r = a("item.armor.equip_gold");
			s = a("item.armor.equip_iron");
			t = a("item.armor.equip_leather");
			u = a("entity.arrow.hit");
			v = a("entity.arrow.hit_player");
			w = a("entity.arrow.shoot");
			x = a("entity.bat.ambient");
			y = a("entity.bat.death");
			z = a("entity.bat.hurt");
			A = a("entity.bat.loop");
			B = a("entity.bat.takeoff");
			C = a("entity.blaze.ambient");
			D = a("entity.blaze.burn");
			E = a("entity.blaze.death");
			F = a("entity.blaze.hurt");
			G = a("entity.blaze.shoot");
			H = a("entity.bobber.splash");
			I = a("entity.bobber.throw");
			J = a("item.bottle.empty");
			K = a("item.bottle.fill");
			L = a("item.bottle.fill_dragonbreath");
			M = a("block.brewing_stand.brew");
			N = a("item.bucket.empty");
			O = a("item.bucket.empty_lava");
			P = a("item.bucket.fill");
			Q = a("item.bucket.fill_lava");
			R = a("entity.cat.ambient");
			S = a("entity.cat.death");
			T = a("entity.cat.hiss");
			U = a("entity.cat.hurt");
			V = a("entity.cat.purr");
			W = a("entity.cat.purreow");
			X = a("block.chest.close");
			Y = a("block.chest.locked");
			Z = a("block.chest.open");
			aa = a("entity.chicken.ambient");
			ab = a("entity.chicken.death");
			ac = a("entity.chicken.egg");
			ad = a("entity.chicken.hurt");
			ae = a("entity.chicken.step");
			af = a("block.chorus_flower.death");
			ag = a("block.chorus_flower.grow");
			ah = a("item.chorus_fruit.teleport");
			ai = a("block.cloth.break");
			aj = a("block.cloth.fall");
			ak = a("block.cloth.hit");
			al = a("block.cloth.place");
			am = a("block.cloth.step");
			an = a("block.comparator.click");
			ao = a("entity.cow.ambient");
			ap = a("entity.cow.death");
			aq = a("entity.cow.hurt");
			ar = a("entity.cow.milk");
			as = a("entity.cow.step");
			at = a("entity.creeper.death");
			au = a("entity.creeper.hurt");
			av = a("entity.creeper.primed");
			aw = a("block.dispenser.dispense");
			ax = a("block.dispenser.fail");
			ay = a("block.dispenser.launch");
			az = a("entity.donkey.ambient");
			aA = a("entity.donkey.angry");
			aB = a("entity.donkey.chest");
			aC = a("entity.donkey.death");
			aD = a("entity.donkey.hurt");
			aE = a("entity.egg.throw");
			aF = a("entity.elder_guardian.ambient");
			aG = a("entity.elder_guardian.ambient_land");
			aH = a("entity.elder_guardian.curse");
			aI = a("entity.elder_guardian.death");
			aJ = a("entity.elder_guardian.death_land");
			aK = a("entity.elder_guardian.flop");
			aL = a("entity.elder_guardian.hurt");
			aM = a("entity.elder_guardian.hurt_land");
			aN = a("item.elytra.flying");
			aO = a("block.enchantment_table.use");
			aP = a("block.enderchest.close");
			aQ = a("block.enderchest.open");
			aR = a("entity.enderdragon.ambient");
			aS = a("entity.enderdragon.death");
			aT = a("entity.enderdragon_fireball.explode");
			aU = a("entity.enderdragon.flap");
			aV = a("entity.enderdragon.growl");
			aW = a("entity.enderdragon.hurt");
			aX = a("entity.enderdragon.shoot");
			aY = a("entity.endereye.launch");
			aZ = a("entity.endermen.ambient");
			ba = a("entity.endermen.death");
			bb = a("entity.endermen.hurt");
			bc = a("entity.endermen.scream");
			bd = a("entity.endermen.stare");
			be = a("entity.endermen.teleport");
			bf = a("entity.endermite.ambient");
			bg = a("entity.endermite.death");
			bh = a("entity.endermite.hurt");
			bi = a("entity.endermite.step");
			bj = a("entity.enderpearl.throw");
			bk = a("block.end_gateway.spawn");
			bl = a("entity.evocation_fangs.attack");
			bm = a("entity.evocation_illager.ambient");
			bn = a("entity.evocation_illager.cast_spell");
			bo = a("entity.evocation_illager.death");
			bp = a("entity.evocation_illager.hurt");
			bq = a("entity.evocation_illager.prepare_attack");
			br = a("entity.evocation_illager.prepare_summon");
			bs = a("entity.evocation_illager.prepare_wololo");
			bt = a("entity.experience_bottle.throw");
			bu = a("entity.experience_orb.pickup");
			bv = a("block.fence_gate.close");
			bw = a("block.fence_gate.open");
			bx = a("item.firecharge.use");
			by = a("entity.firework.blast");
			bz = a("entity.firework.blast_far");
			bA = a("entity.firework.large_blast");
			bB = a("entity.firework.large_blast_far");
			bC = a("entity.firework.launch");
			bD = a("entity.firework.shoot");
			bE = a("entity.firework.twinkle");
			bF = a("entity.firework.twinkle_far");
			bG = a("block.fire.ambient");
			bH = a("block.fire.extinguish");
			bI = a("item.flintandsteel.use");
			bJ = a("block.furnace.fire_crackle");
			bK = a("entity.generic.big_fall");
			bL = a("entity.generic.burn");
			bM = a("entity.generic.death");
			bN = a("entity.generic.drink");
			bO = a("entity.generic.eat");
			bP = a("entity.generic.explode");
			bQ = a("entity.generic.extinguish_fire");
			bR = a("entity.generic.hurt");
			bS = a("entity.generic.small_fall");
			bT = a("entity.generic.splash");
			bU = a("entity.generic.swim");
			bV = a("entity.ghast.ambient");
			bW = a("entity.ghast.death");
			bX = a("entity.ghast.hurt");
			bY = a("entity.ghast.scream");
			bZ = a("entity.ghast.shoot");
			ca = a("entity.ghast.warn");
			cb = a("block.glass.break");
			cc = a("block.glass.fall");
			cd = a("block.glass.hit");
			ce = a("block.glass.place");
			cf = a("block.glass.step");
			cg = a("block.grass.break");
			ch = a("block.grass.fall");
			ci = a("block.grass.hit");
			cj = a("block.grass.place");
			ck = a("block.grass.step");
			cl = a("block.gravel.break");
			cm = a("block.gravel.fall");
			cn = a("block.gravel.hit");
			co = a("block.gravel.place");
			cp = a("block.gravel.step");
			cq = a("entity.guardian.ambient");
			cr = a("entity.guardian.ambient_land");
			cs = a("entity.guardian.attack");
			ct = a("entity.guardian.death");
			cu = a("entity.guardian.death_land");
			cv = a("entity.guardian.flop");
			cw = a("entity.guardian.hurt");
			cx = a("entity.guardian.hurt_land");
			cy = a("item.hoe.till");
			cz = a("entity.horse.ambient");
			cA = a("entity.horse.angry");
			cB = a("entity.horse.armor");
			cC = a("entity.horse.breathe");
			cD = a("entity.horse.death");
			cE = a("entity.horse.eat");
			cF = a("entity.horse.gallop");
			cG = a("entity.horse.hurt");
			cH = a("entity.horse.jump");
			cI = a("entity.horse.land");
			cJ = a("entity.horse.saddle");
			cK = a("entity.horse.step");
			cL = a("entity.horse.step_wood");
			cM = a("entity.hostile.big_fall");
			cN = a("entity.hostile.death");
			cO = a("entity.hostile.hurt");
			cP = a("entity.hostile.small_fall");
			cQ = a("entity.hostile.splash");
			cR = a("entity.hostile.swim");
			cS = a("entity.husk.ambient");
			cT = a("entity.husk.death");
			cU = a("entity.husk.hurt");
			cV = a("entity.husk.step");
			cW = a("entity.irongolem.attack");
			cX = a("entity.irongolem.death");
			cY = a("entity.irongolem.hurt");
			cZ = a("entity.irongolem.step");
			da = a("block.iron_door.close");
			db = a("block.iron_door.open");
			dc = a("block.iron_trapdoor.close");
			dd = a("block.iron_trapdoor.open");
			de = a("entity.itemframe.add_item");
			df = a("entity.itemframe.break");
			dg = a("entity.itemframe.place");
			dh = a("entity.itemframe.remove_item");
			di = a("entity.itemframe.rotate_item");
			dj = a("entity.item.break");
			dk = a("entity.item.pickup");
			dl = a("block.ladder.break");
			dm = a("block.ladder.fall");
			dn = a("block.ladder.hit");
			do = a("block.ladder.place");
			dp = a("block.ladder.step");
			dq = a("block.lava.ambient");
			dr = a("block.lava.extinguish");
			ds = a("block.lava.pop");
			dt = a("entity.leashknot.break");
			du = a("entity.leashknot.place");
			dv = a("block.lever.click");
			dw = a("entity.lightning.impact");
			dx = a("entity.lightning.thunder");
			dy = a("entity.lingeringpotion.throw");
			dz = a("entity.llama.ambient");
			dA = a("entity.llama.angry");
			dB = a("entity.llama.chest");
			dC = a("entity.llama.death");
			dD = a("entity.llama.eat");
			dE = a("entity.llama.hurt");
			dF = a("entity.llama.spit");
			dG = a("entity.llama.step");
			dH = a("entity.llama.swag");
			dI = a("entity.magmacube.death");
			dJ = a("entity.magmacube.hurt");
			dK = a("entity.magmacube.jump");
			dL = a("entity.magmacube.squish");
			dM = a("block.metal.break");
			dN = a("block.metal.fall");
			dO = a("block.metal.hit");
			dP = a("block.metal.place");
			dQ = a("block.metal_pressureplate.click_off");
			dR = a("block.metal_pressureplate.click_on");
			dS = a("block.metal.step");
			dT = a("entity.minecart.inside");
			dU = a("entity.minecart.riding");
			dV = a("entity.mooshroom.shear");
			dW = a("entity.mule.ambient");
			dX = a("entity.mule.chest");
			dY = a("entity.mule.death");
			dZ = a("entity.mule.hurt");
			ea = a("music.creative");
			eb = a("music.credits");
			ec = a("music.dragon");
			ed = a("music.end");
			ee = a("music.game");
			ef = a("music.menu");
			eg = a("music.nether");
			eh = a("block.note.basedrum");
			ei = a("block.note.bass");
			ej = a("block.note.harp");
			ek = a("block.note.hat");
			el = a("block.note.pling");
			em = a("block.note.snare");
			en = a("entity.painting.break");
			eo = a("entity.painting.place");
			ep = a("entity.pig.ambient");
			eq = a("entity.pig.death");
			er = a("entity.pig.hurt");
			es = a("entity.pig.saddle");
			et = a("entity.pig.step");
			eu = a("block.piston.contract");
			ev = a("block.piston.extend");
			ew = a("entity.player.attack.crit");
			ex = a("entity.player.attack.knockback");
			ey = a("entity.player.attack.nodamage");
			ez = a("entity.player.attack.strong");
			eA = a("entity.player.attack.sweep");
			eB = a("entity.player.attack.weak");
			eC = a("entity.player.big_fall");
			eD = a("entity.player.breath");
			eE = a("entity.player.burp");
			eF = a("entity.player.death");
			eG = a("entity.player.hurt");
			eH = a("entity.player.levelup");
			eI = a("entity.player.small_fall");
			eJ = a("entity.player.splash");
			eK = a("entity.player.swim");
			eL = a("entity.polar_bear.ambient");
			eM = a("entity.polar_bear.baby_ambient");
			eN = a("entity.polar_bear.death");
			eO = a("entity.polar_bear.hurt");
			eP = a("entity.polar_bear.step");
			eQ = a("entity.polar_bear.warning");
			eR = a("block.portal.ambient");
			eS = a("block.portal.travel");
			eT = a("block.portal.trigger");
			eU = a("entity.rabbit.ambient");
			eV = a("entity.rabbit.attack");
			eW = a("entity.rabbit.death");
			eX = a("entity.rabbit.hurt");
			eY = a("entity.rabbit.jump");
			eZ = a("record.11");
			fa = a("record.13");
			fb = a("record.blocks");
			fc = a("record.cat");
			fd = a("record.chirp");
			fe = a("record.far");
			ff = a("record.mall");
			fg = a("record.mellohi");
			fh = a("record.stal");
			fi = a("record.strad");
			fj = a("record.wait");
			fk = a("record.ward");
			fl = a("block.redstone_torch.burnout");
			fm = a("block.sand.break");
			fn = a("block.sand.fall");
			fo = a("block.sand.hit");
			fp = a("block.sand.place");
			fq = a("block.sand.step");
			fr = a("entity.sheep.ambient");
			fs = a("entity.sheep.death");
			ft = a("entity.sheep.hurt");
			fu = a("entity.sheep.shear");
			fv = a("entity.sheep.step");
			fw = a("item.shield.block");
			fx = a("item.shield.break");
			fy = a("item.shovel.flatten");
			fz = a("entity.shulker.ambient");
			fA = a("block.shulker_box.close");
			fB = a("block.shulker_box.open");
			fC = a("entity.shulker_bullet.hit");
			fD = a("entity.shulker_bullet.hurt");
			fE = a("entity.shulker.close");
			fF = a("entity.shulker.death");
			fG = a("entity.shulker.hurt");
			fH = a("entity.shulker.hurt_closed");
			fI = a("entity.shulker.open");
			fJ = a("entity.shulker.shoot");
			fK = a("entity.shulker.teleport");
			fL = a("entity.silverfish.ambient");
			fM = a("entity.silverfish.death");
			fN = a("entity.silverfish.hurt");
			fO = a("entity.silverfish.step");
			fP = a("entity.skeleton.ambient");
			fQ = a("entity.skeleton.death");
			fR = a("entity.skeleton_horse.ambient");
			fS = a("entity.skeleton_horse.death");
			fT = a("entity.skeleton_horse.hurt");
			fU = a("entity.skeleton.hurt");
			fV = a("entity.skeleton.shoot");
			fW = a("entity.skeleton.step");
			fX = a("entity.slime.attack");
			fY = a("block.slime.break");
			fZ = a("entity.slime.death");
			ga = a("block.slime.fall");
			gb = a("block.slime.hit");
			gc = a("entity.slime.hurt");
			gd = a("entity.slime.jump");
			ge = a("block.slime.place");
			gf = a("entity.slime.squish");
			gg = a("block.slime.step");
			gh = a("entity.small_magmacube.death");
			gi = a("entity.small_magmacube.hurt");
			gj = a("entity.small_magmacube.squish");
			gk = a("entity.small_slime.death");
			gl = a("entity.small_slime.hurt");
			gm = a("entity.small_slime.jump");
			gn = a("entity.small_slime.squish");
			go = a("entity.snowball.throw");
			gp = a("entity.snowman.ambient");
			gq = a("entity.snowman.death");
			gr = a("entity.snowman.hurt");
			gs = a("entity.snowman.shoot");
			gt = a("block.snow.break");
			gu = a("block.snow.fall");
			gv = a("block.snow.hit");
			gw = a("block.snow.place");
			gx = a("block.snow.step");
			gy = a("entity.spider.ambient");
			gz = a("entity.spider.death");
			gA = a("entity.spider.hurt");
			gB = a("entity.spider.step");
			gC = a("entity.splash_potion.break");
			gD = a("entity.splash_potion.throw");
			gE = a("entity.squid.ambient");
			gF = a("entity.squid.death");
			gG = a("entity.squid.hurt");
			gH = a("block.stone.break");
			gI = a("block.stone_button.click_off");
			gJ = a("block.stone_button.click_on");
			gK = a("block.stone.fall");
			gL = a("block.stone.hit");
			gM = a("block.stone.place");
			gN = a("block.stone_pressureplate.click_off");
			gO = a("block.stone_pressureplate.click_on");
			gP = a("block.stone.step");
			gQ = a("entity.stray.ambient");
			gR = a("entity.stray.death");
			gS = a("entity.stray.hurt");
			gT = a("entity.stray.step");
			gU = a("enchant.thorns.hit");
			gV = a("entity.tnt.primed");
			gW = a("item.totem.use");
			gX = a("block.tripwire.attach");
			gY = a("block.tripwire.click_off");
			gZ = a("block.tripwire.click_on");
			ha = a("block.tripwire.detach");
			hb = a("ui.button.click");
			hc = a("entity.vex.ambient");
			hd = a("entity.vex.charge");
			he = a("entity.vex.death");
			hf = a("entity.vex.hurt");
			hg = a("entity.villager.ambient");
			hh = a("entity.villager.death");
			hi = a("entity.villager.hurt");
			hj = a("entity.villager.no");
			hk = a("entity.villager.trading");
			hl = a("entity.villager.yes");
			hm = a("entity.vindication_illager.ambient");
			hn = a("entity.vindication_illager.death");
			ho = a("entity.vindication_illager.hurt");
			hp = a("block.waterlily.place");
			hq = a("block.water.ambient");
			hr = a("weather.rain");
			hs = a("weather.rain.above");
			ht = a("entity.witch.ambient");
			hu = a("entity.witch.death");
			hv = a("entity.witch.drink");
			hw = a("entity.witch.hurt");
			hx = a("entity.witch.throw");
			hy = a("entity.wither.ambient");
			hz = a("entity.wither.break_block");
			hA = a("entity.wither.death");
			hB = a("entity.wither.hurt");
			hC = a("entity.wither.shoot");
			hD = a("entity.wither_skeleton.ambient");
			hE = a("entity.wither_skeleton.death");
			hF = a("entity.wither_skeleton.hurt");
			hG = a("entity.wither_skeleton.step");
			hH = a("entity.wither.spawn");
			hI = a("entity.wolf.ambient");
			hJ = a("entity.wolf.death");
			hK = a("entity.wolf.growl");
			hL = a("entity.wolf.howl");
			hM = a("entity.wolf.hurt");
			hN = a("entity.wolf.pant");
			hO = a("entity.wolf.shake");
			hP = a("entity.wolf.step");
			hQ = a("entity.wolf.whine");
			hR = a("block.wooden_door.close");
			hS = a("block.wooden_door.open");
			hT = a("block.wooden_trapdoor.close");
			hU = a("block.wooden_trapdoor.open");
			hV = a("block.wood.break");
			hW = a("block.wood_button.click_off");
			hX = a("block.wood_button.click_on");
			hY = a("block.wood.fall");
			hZ = a("block.wood.hit");
			ia = a("block.wood.place");
			ib = a("block.wood_pressureplate.click_off");
			ic = a("block.wood_pressureplate.click_on");
			id = a("block.wood.step");
			ie = a("entity.zombie.ambient");
			if = a("entity.zombie.attack_door_wood");
			ig = a("entity.zombie.attack_iron_door");
			ih = a("entity.zombie.break_door_wood");
			ii = a("entity.zombie.death");
			ij = a("entity.zombie_horse.ambient");
			ik = a("entity.zombie_horse.death");
			il = a("entity.zombie_horse.hurt");
			im = a("entity.zombie.hurt");
			in = a("entity.zombie.infect");
			io = a("entity.zombie_pig.ambient");
			ip = a("entity.zombie_pig.angry");
			iq = a("entity.zombie_pig.death");
			ir = a("entity.zombie_pig.hurt");
			is = a("entity.zombie.step");
			it = a("entity.zombie_villager.ambient");
			iu = a("entity.zombie_villager.converted");
			iv = a("entity.zombie_villager.cure");
			iw = a("entity.zombie_villager.death");
			ix = a("entity.zombie_villager.hurt");
			iy = a("entity.zombie_villager.step");
		}
	}
}
